# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='advice',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reflection',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='category',
            field=models.CharField(choices=[('FACILITY', '學校設備'), ('RESTAURANT', '餐廳食物'), ('ACADEMY', '課業學習'), ('ACTIVITY', '學生活動'), ('OTHER', '其他')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
