# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflect', '0002_auto_20170127_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='advice',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
