# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reflect', '0004_auto_20170131_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reflectionID',
        ),
    ]
