# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reflect', '0005_remove_reply_reflectionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reflection',
            name='replies',
        ),
        migrations.AddField(
            model_name='reply',
            name='reflection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reflect.Reflection'),
        ),
    ]
