# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reflect', '0006_auto_20170201_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reflection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reflect.Reflection'),
        ),
    ]
