# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reflect', '0008_firstvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstvisit',
            name='visited',
        ),
        migrations.AddField(
            model_name='firstvisit',
            name='reflection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reflect.Reflection'),
        ),
    ]
