# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflect', '0010_auto_20170201_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='finish',
        ),
        migrations.AddField(
            model_name='state',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
